server:
  port: 8002

spring:
  application:
    name: cardio-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cardio_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        cardio-workout-created-out-0:
          destination: cardio-workout-created
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: cardio-service
            client-secret: Vf6F0kcyu6riJXa3VUfsRyNsUit9qqPV
            client-name: cardio-service
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/easy-fitness

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    # Spring Security OAuth2 полная отладка
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE


    # JWT валидация и claims
    org.springframework.security.oauth2.jwt: TRACE
    org.springframework.security.oauth2.server.resource.authentication: TRACE

    # Keycloak/JWT детали
    org.keycloak: DEBUG

    # HTTP запросы с токенами (осторожно в проде)
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http: DEBUG
    org.springframework.security.authorization: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.oauth2.server.resource.web: TRACE
  # Дополнительно для Keycloak adapter




